### ISSUE TITLE
[Python] 방문 길이

### ISSUE THREAD

**Issue by ChanYangYu** [soongding/algorithm#12]
## 솔루션
- dy, dx : 상,하,좌,우 이동 배열
- mp : U,D,L,R => dy, dx인덱스 매핑 dictionary
- ch : ch[x][y][yy][xx] => x, y에서 yy, xx로 방문 여부 체크
- 로직
    1. ( y, x ) = ( 5, 5 )에서 시작하여 U,D,L,R 명령어에 맞게 이동한 ( yy, xx )를 구한다.
    2. ( yy, xx )가 범위[ 0 ~ 10 ]를 벗어나면 해당 명령어 무시
    3. ( y, x ) ⇒ ( yy, xx ) 처음 가는 길인 경우
        1. ch[y][x][yy][xx], ch[yy][xx][y][x] 양방향 방문체크
        2. answer 횟수 증가
    4. ( yy, xx )로 이동
 
`cpp로 작성하려고 했는데 이미 문제를 풀어서 python으로 풀었습니다! `
## 코드
```python
import numpy as np

dy = [-1,1,0,0]
dx = [0,0,1,-1]
mp = {'U':0, 'D':1, 'R':2, 'L':3}

def solution(dirs):
    ch = np.zeros((11,11,11,11))
    answer = 0
    y, x = (5,5)
    
    for d in dirs:
        yy =  y + dy[mp[d]]
        xx = x + dx[mp[d]]
        
        if yy < 0 or yy > 10 or xx < 0 or xx > 10:
            continue
        elif ch[y][x][yy][xx] == 0:
            ch[y][x][yy][xx] = 1
            ch[yy][xx][y][x] = 1
            answer += 1
        y = yy
        x = xx
    return answer
```

**Comment by Dev-Beom** [comment]
4차원 배열로 하는것도 좋아보인다..
넘파이 zeros로 배열 0으로 박아주는것도 개사기네..
