### ISSUE TITLE
[Javascript] 입실 퇴실

### ISSUE THREAD

**Issue by yuchanleeme** [soongding/algorithm#19]
### 처음 접근
1. 처음에는 단순히 완탐으로 모든 조합을 만들어서 푸려고 했습니다.  -> 하다보니 로직이 꼬여서 실패
2. 투포인터를 이용해서 각 enter, leave 조건을 보면서 하나씩 탐색하려 했습니다. -> 또 하다보니 위에 처럼 완탐으로 가게돼서 실패

### 최종 풀이
1. 먼저 inRoom (현재 방의 인원들의 정보), res(각 번호가 만난 사람의 숫자) 2개의 배열을 만듭니다.
2. 이제 leave 배열을 순회하면서 각 인원이 퇴장을 할 때마다 그 인원이 퇴장하기 전까지 enter에 있는 사람들을 inRoom에 추가시킵니다.
 ex) enter [`1` , 3, 2 ,4]  leave [`2`, 1 ,3 4] 이라면 leave[0] = 2가 입장할때까지 inRoom에 사람들을 채웁니다.
      => inRoom[1, 3, 2] enter[1,3,`2`,4] , leave[2,`1`,3,4] , (각 ` ` 는 지금 가리키고 있는 idx)
3. 이제 inRoom에 있는 인원 만큼 지금 퇴장하는 번호가 추가로 만난다고 생각하면 됩니다.
4. 그리고 inRoom에 인원들의 값을 1 추가시켜줍니다. (leave 한 사람을 만났으니까)
5. 이렇게 leave 배열의 마지막까지 돌면서 결과를 리턴합니다.

## 코드
``` jsx
function solution(enter, leave) {
  let inRoom = []
  let res = []
  for(let i = 0; i < enter.length; i++){
    res.push(0)
  }

  let idx = 0;
  for (const whoLeave of leave) {
    while(!inRoom.includes(whoLeave)){
      inRoom.push(enter[idx++])
    }
    
    let idxOfRoom = inRoom.indexOf(whoLeave);
    inRoom.splice(idxOfRoom,1)

    res[whoLeave-1] += inRoom.length
    for (const whoInRoom of inRoom) {
      res[whoInRoom-1]++
    }
  }

  return res
}
```

**Comment by Dev-Beom** [comment]
아니 이렇게 간결해진다고..?
